<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eyes_Face</name>
   <tag></tag>
   <elementGuidId>3fe2f447-b9ba-4ced-83d2-fa53c4132fa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Face']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Face&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81a90b22-f3ae-490f-a469-fc651bc9152f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input muiltr-1m9pwf3</value>
      <webElementGuid>79690909-f3c4-4c03-8084-73f54cb566a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Face</value>
      <webElementGuid>7d22aca6-e75d-4131-99e1-a99e26ad3a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b2546b10-c660-4f87-91ec-4daeb9e4c017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5579367a-31b5-4046-8e81-e8f9cf95da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root dropdown-menus filters-panel MuiModal-root muiltr-itg9sh-MuiModal-root-MuiPopover-root-MuiMenu-root&quot;]/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPopover-paper muiltr-wwomeb-MuiPaper-root-MuiMenu-paper-MuiPopover-paper&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list muiltr-6hp17o-MuiList-root-MuiMenu-list&quot;]/li[@class=&quot;MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters muiltr-uyhvtt-MuiButtonBase-root-MuiMenuItem-root&quot;]/div[@class=&quot;muiltr-1yxnjc1&quot;]/ul[@class=&quot;MuiList-root MuiList-padding charts filters-items muiltr-h4y409-MuiList-root&quot;]/li[@class=&quot;MuiListItem-root MuiListItem-gutters MuiListItem-padding muiltr-1evxpc3-MuiListItem-root&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd muiltr-j204z7-MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-root MuiCheckbox-colorPrimary muiltr-ro760c-MuiButtonBase-root-MuiCheckbox-root&quot;]/input[@class=&quot;PrivateSwitchBase-input muiltr-1m9pwf3&quot;]</value>
      <webElementGuid>96adda3b-18de-456d-ac9f-1f6e5b8469d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Face']</value>
      <webElementGuid>25133ce4-094b-40c0-9d06-bc19672f2d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li[7]/label/span/input</value>
      <webElementGuid>cf8c7119-3761-4f04-8dd0-7d6f51924f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Face' and @type = 'checkbox']</value>
      <webElementGuid>759f8b9c-2eba-4cd3-933b-a1ed892a37d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
