<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_TEXT</name>
   <tag></tag>
   <elementGuidId>bb7315a8-bd8b-4c86-80f9-db4ad5990a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='standard-multiline-static']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#standard-multiline-static</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03461e9d-df31-4189-88cc-1c4cf2a1b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ec4c0b40-493f-4958-8786-2f702194cd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f200bb4-2b0f-4f08-826e-d1f8bd549202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>standard-multiline-static</value>
      <webElementGuid>61b61200-3f10-4743-958f-13228c1c89cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type something here...</value>
      <webElementGuid>136b2ddd-a6d5-4b31-9f78-988beb33e6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e680323-7850-4b9b-8c70-7eec7afc58b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input MuiInputBase-inputMultiline muiltr-7209ej-MuiInputBase-input-MuiFilledInput-input</value>
      <webElementGuid>78b77e96-2e16-43de-a247-f8fac4510944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>bdb880a6-9a64-4430-ad60-6a7d33580cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;standard-multiline-static&quot;)</value>
      <webElementGuid>6dd4d1ce-9e8a-4ad6-b81c-b80fd08e4623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='standard-multiline-static']</value>
      <webElementGuid>23d808a6-ff54-4921-9c0a-d0ad29f39a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div[2]/div[2]/div/div[11]/div/textarea</value>
      <webElementGuid>3a75202c-f31f-496f-af17-360cd2458b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new comment'])[1]/following::textarea[1]</value>
      <webElementGuid>4a202ee2-1803-4fdf-870d-d6e2dc92832b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::textarea[1]</value>
      <webElementGuid>615f601c-b567-4472-bf41-ba4617e9e101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[2]</value>
      <webElementGuid>bb98ca48-0717-43d2-b344-30ab5d79da69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[1]/preceding::textarea[2]</value>
      <webElementGuid>3b892090-b56f-4e2c-80f7-2b1247698c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEXT']/parent::*</value>
      <webElementGuid>60d2b89e-003f-4a6a-8dad-3704aaa84f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3a0dd127-de87-4056-8cc9-95c76ef5f1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'standard-multiline-static' and @placeholder = 'Type something here...' and @type = 'text' and (text() = 'TEXT' or . = 'TEXT')]</value>
      <webElementGuid>11c4e183-32ab-40e8-94f6-8577cd06edf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
