<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test case pas</name>
   <tag></tag>
   <elementGuidId>3f04b595-6649-40a5-9e9d-5a1c05e90678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='standard-multiline-static']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#standard-multiline-static</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>53b706b8-5106-4a34-93b2-3c544d70795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d32856a1-c128-4560-a5b3-f090871d6590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cae7262d-538b-4c74-9515-2a5cfa100975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>standard-multiline-static</value>
      <webElementGuid>3eb2c389-3f70-4043-912e-6cbdffed7908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type something here...</value>
      <webElementGuid>abc635ac-7936-4f37-9c16-57e13a06c36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>503d3f4c-fef9-478a-9864-cc35079a4355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input MuiInputBase-inputMultiline muiltr-7209ej-MuiInputBase-input-MuiFilledInput-input</value>
      <webElementGuid>f8e60324-d057-4f33-87fe-4a08a3ba6549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test case pas</value>
      <webElementGuid>8045f87c-7daf-4e1b-806f-5ad5d894c478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;standard-multiline-static&quot;)</value>
      <webElementGuid>97289a7f-7d92-465e-aec5-10f04eaa9ee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='standard-multiline-static']</value>
      <webElementGuid>52b597c0-f098-4338-bcf3-1fa875f86024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div[2]/div[2]/div/div[11]/div/textarea</value>
      <webElementGuid>8bc9ffb5-1528-4f91-b08d-39c8f951cf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new comment'])[1]/following::textarea[1]</value>
      <webElementGuid>faf2fba5-30ff-496f-8bf9-2567b157dcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::textarea[1]</value>
      <webElementGuid>8be00151-e722-4bb6-93a8-54f8eb152a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[2]</value>
      <webElementGuid>621f867a-d1d2-401a-acf8-650ea76883d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[1]/preceding::textarea[2]</value>
      <webElementGuid>221325dd-9056-461e-b33f-aee1c82cc283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test case pas']/parent::*</value>
      <webElementGuid>a8f11eca-b39b-4c9f-9bcf-1e1f7b0968ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>295a6bba-27e1-4d34-90b9-26c0b315348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'standard-multiline-static' and @placeholder = 'Type something here...' and @type = 'text' and (text() = 'Test case pas' or . = 'Test case pas')]</value>
      <webElementGuid>7cbda82c-a561-4a69-b69f-93b539ddc661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
