<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>bbb4e21b-c426-4412-95e5-cb9b6b62d611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='basic-button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.muirtl-k008qs > #basic-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2488124-a3be-4947-bf11-3972c119e9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium utility-dd-menu muirtl-1bq52xl-MuiButtonBase-root-MuiButton-root</value>
      <webElementGuid>d733802b-5a16-4a69-9fd1-2e46223999b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8864b9a7-54b0-4f8c-8adc-70e771f298da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>207b0f37-771b-4ed5-8846-8e52eb79496b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-button</value>
      <webElementGuid>86cee3ba-913c-46d9-9ece-1de0ca3e4426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d92b0c61-4ace-4efb-b259-8635670ccba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>f234aa71-65cc-49ea-b69d-08a239121d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex muirtl-1928xwl&quot;]/div[@class=&quot;utility-bar MuiBox-root muirtl-0&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed app-bar mui-fixed muirtl-ii4kgp-MuiPaper-root-MuiAppBar-root&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular tool-bar muirtl-rugrh9-MuiToolbar-root&quot;]/div[@class=&quot;MuiBox-root muirtl-k008qs&quot;]/button[@id=&quot;basic-button&quot;]</value>
      <webElementGuid>72f7cebb-2dd5-40d2-a541-3ae0d812d14c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='basic-button'])[3]</value>
      <webElementGuid>726bc1d2-aa89-43f9-8a9d-d1bbfd0dce96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/header/div/div[2]/button</value>
      <webElementGuid>18d368f0-1969-4182-b3a1-eeebc2fd4b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muhammad Talha Khan a.k.a Afghani'])[1]/following::button[1]</value>
      <webElementGuid>6df35bc5-1a79-46f2-9252-ff5f01704993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لوحة القيادة'])[2]/preceding::button[1]</value>
      <webElementGuid>b527dea6-eadc-4631-88de-52410682224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::button[2]</value>
      <webElementGuid>c904e978-4d4f-4897-baa4-814c8776cc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='العربية']/parent::*</value>
      <webElementGuid>3948131b-e60d-4db2-85f6-346edab632bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>182e50a9-4c6a-4425-b88b-c009fdeb5f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'basic-button' and (text() = 'العربية' or . = 'العربية')]</value>
      <webElementGuid>7d8c488b-b2d6-4986-a65c-07292ef8854b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
