<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee ID_empId</name>
   <tag></tag>
   <elementGuidId>5c9c4403-8e97-4c72-b392-7019a663169d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Custom-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Custom-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c8dc216-6755-4247-b2c9-74562cdda8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6f59e54-d379-4e21-a219-d516ba6bff78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Custom-input</value>
      <webElementGuid>d79b99be-a9af-403d-8553-ffc145c123e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empId</value>
      <webElementGuid>2c15bf09-0605-41dd-8a6c-d94bf8ffeeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee ID</value>
      <webElementGuid>0b68757c-ff7f-4711-a4cb-89b2cffc6d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2006c48a-1fb9-4e39-ac0a-69dff2c925f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInputBase-inputSizeSmall muiltr-7dqvty-MuiInputBase-input</value>
      <webElementGuid>6e76a6b4-0a05-4b16-b60f-a491f4d426d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Custom-input&quot;)</value>
      <webElementGuid>5fbc6a36-d7be-484f-855e-efe3faa9f4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Custom-input']</value>
      <webElementGuid>8704c3a7-ced3-49a6-a984-6f5ca5bdbbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/form/div/div/input</value>
      <webElementGuid>da4dda32-ef26-468d-a7f6-cbfd1f5b298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>70d152f9-c7f0-49bb-845c-40fe4bc12ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Custom-input' and @name = 'empId' and @placeholder = 'Employee ID' and @type = 'text']</value>
      <webElementGuid>142f8810-4df5-4cbd-8664-e8873d9824a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
