<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee ID_empId</name>
   <tag></tag>
   <elementGuidId>e5fbee1f-af91-4871-866e-8368ba04c839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Custom-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Custom-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaca05b8-3458-4b45-ab3d-6c67802a05c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68c1e087-98a5-4242-85ec-973caebeff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Custom-input</value>
      <webElementGuid>31cafd10-c5a5-4573-929d-dc5a0c023855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empId</value>
      <webElementGuid>7731f543-ba0f-4c5d-9b2a-0e4b91b6d545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee ID</value>
      <webElementGuid>776fd1c1-3b22-447a-a966-7270c62c3ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59360a02-a5cf-4efc-bb91-4a3e1282a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInputBase-inputSizeSmall muiltr-7dqvty-MuiInputBase-input</value>
      <webElementGuid>ddc9f3e0-29b9-453d-b2cb-20307e9a5709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Custom-input&quot;)</value>
      <webElementGuid>02c14857-6120-489d-a3c5-6de14254b3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Custom-input']</value>
      <webElementGuid>53b94520-701d-4e9f-9c7d-3bc54fdbfc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/form/div/div/input</value>
      <webElementGuid>f3400b18-07b6-409e-8dd7-56bfc9e8b4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e83d4a84-eae6-4341-b0b9-58de27358870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Custom-input' and @name = 'empId' and @placeholder = 'Employee ID' and @type = 'text']</value>
      <webElementGuid>003aa882-eddf-42da-9ca5-dd3d35f77b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
