<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Negative</name>
   <tag></tag>
   <elementGuidId>cad39c47-a597-4f96-a478-9fd5dacc41f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Negative']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-legend-item.highcharts-bar-series.highcharts-color-undefined.highcharts-series-1 > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c1b0fad-b681-4987-97e0-920b87032a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>f2320830-8aea-46e1-a173-650b592e1bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>68dfd106-232d-47dd-81f2-29481f42b47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>b9f51319-d8f6-40a3-888f-51c01e603304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>af3fcd84-e81c-4bbb-81c6-a467aa86a650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Negative</value>
      <webElementGuid>c509547b-6fbd-4777-a841-ee7d1e4624fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-tz9bjuq-13&quot;)/svg[@class=&quot;highcharts-root highcharts-legend-series-active&quot;]/g[@class=&quot;highcharts-legend highcharts-no-tooltip&quot;]/g[1]/g[1]/g[@class=&quot;highcharts-legend-item highcharts-bar-series highcharts-color-undefined highcharts-series-1&quot;]/text[1]</value>
      <webElementGuid>f096eec6-1e48-4fcc-b523-a0b5d80cfa94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Negative']/parent::*</value>
      <webElementGuid>5e09437f-1b84-439a-b54b-1575715040f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Negative' or . = 'Negative')]</value>
      <webElementGuid>5c8f9089-d738-468f-8a94-ddcfc984c778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
