<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_100</name>
   <tag></tag>
   <elementGuidId>9c141f98-9744-4b62-af74-81e118bfeebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='100']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-axis-labels.highcharts-yaxis-labels > text:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d63149c3-39d7-4c1c-a171-84caa621301b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>400.4444332122803</value>
      <webElementGuid>a8b541bb-74cd-4ed3-9172-9f99db62f447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>7343eeb1-1f89-4125-b41e-9bbbf05547b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(0,0)</value>
      <webElementGuid>fc9488c8-c5c8-432a-a3ab-5d2fe200efb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>336</value>
      <webElementGuid>f659a634-ad80-4c06-aedb-b6a149fb74e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1da0b8c-0d2a-42c6-9fe4-0a6d392ee7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1c52166d-8982-4e7e-9cdb-8c30c91f99fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-133vui9-13&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-axis-labels highcharts-yaxis-labels&quot;]/text[2]</value>
      <webElementGuid>775ec260-9413-4ff4-95e3-74b91f29cef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100']/parent::*</value>
      <webElementGuid>cc8113bc-c8fa-46e8-a9d6-82a98ca672ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '100' or . = '100')]</value>
      <webElementGuid>dd0527a8-77b4-40df-b4fc-7aa57469eb99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
