<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Values</name>
   <tag></tag>
   <elementGuidId>1ebecb51-6ed7-4416-bca7-f4907e342789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Values']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#highcharts-133vui9-88 > svg.highcharts-root > g.highcharts-axis.highcharts-yaxis > text.highcharts-axis-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbc08ddf-afc5-43a8-96df-2ccabd567c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>16.488866806030273</value>
      <webElementGuid>0b20dda6-d479-4849-9a79-d998421d5a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>da61e95a-fe69-4a5e-af8d-a83ac6128702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>0e1cbf33-b069-472f-b4ed-3e10c8c44725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(0,0) rotate(270 16.488866806030273 194)</value>
      <webElementGuid>1c532d05-0001-4f17-8cf9-04b74f364eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-axis-title</value>
      <webElementGuid>7d13bef8-8942-4018-92d9-d5491797541e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>194</value>
      <webElementGuid>fcc09eca-7aa7-4eff-90ad-40dced25355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Values</value>
      <webElementGuid>78bda684-b516-4090-bc10-f3b9e3ef2fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-133vui9-88&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-axis highcharts-yaxis&quot;]/text[@class=&quot;highcharts-axis-title&quot;]</value>
      <webElementGuid>9e687978-1072-4be5-a237-0bd0f7052836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Values']/parent::*</value>
      <webElementGuid>6f9d686f-3eef-48d7-a228-0e372f7cd14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Values' or . = 'Values')]</value>
      <webElementGuid>931301bc-7a41-4637-b4c3-81b737721782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
