<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_</name>
   <tag></tag>
   <elementGuidId>a5edfbaa-87ce-4224-83f0-21843910dd64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.MuiTypography-root.MuiTypography-h5.on-boarding-heading.muirtl-15ewt6q-MuiTypography-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>944c006c-f163-4e51-91f9-14bfda6e534c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 on-boarding-heading muirtl-15ewt6q-MuiTypography-root</value>
      <webElementGuid>e3659c31-fc17-4ba0-980d-fa3485988a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>849ee34f-694c-459e-a690-a13a553b3ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;muirtl-1928xwl&quot;]/main[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg auth-container muirtl-9a012d-MuiContainer-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container onboarding-grid muirtl-1ubopdy-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 muirtl-1y88gue-MuiGrid-root&quot;]/h1[@class=&quot;MuiTypography-root MuiTypography-h5 on-boarding-heading muirtl-15ewt6q-MuiTypography-root&quot;]</value>
      <webElementGuid>391de605-9ca4-409c-af0f-10435bcc1883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div/h1</value>
      <webElementGuid>e02afea8-1b13-44ef-a548-09b1b64986aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العربية'])[1]/following::h1[1]</value>
      <webElementGuid>9b955daa-3faf-4ea0-bc25-480f0a254abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هوية الموظف'])[1]/preceding::h1[1]</value>
      <webElementGuid>85056c48-f636-4697-a9b3-9ee4da29fabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التالي'])[1]/preceding::h1[1]</value>
      <webElementGuid>80f78e27-1bbf-4f43-8da0-5c07a4756141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تسجيل الدخول']/parent::*</value>
      <webElementGuid>da8b22ab-4ad9-4fd5-b771-8aa6832dcb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>eb12549e-6e3d-445f-b7d7-fa937e40be2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>a64c2190-3b58-4f6f-9299-78d9b93d8e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
