<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Last 7 days_MuiBackdrop-root MuiBackdro_f20361</name>
   <tag></tag>
   <elementGuidId>0be6ef41-2194-436a-aefb-2bc8fbdc3122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBackdrop-root.MuiBackdrop-invisible.MuiModal-backdrop.muiltr-g3hgs1-MuiBackdrop-root-MuiModal-backdrop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fade-menu']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>379b1386-0d3b-491b-b5ae-5f92ef8614fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03e45d50-d948-44ce-8650-9d138d56e20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBackdrop-root MuiBackdrop-invisible MuiModal-backdrop muiltr-g3hgs1-MuiBackdrop-root-MuiModal-backdrop</value>
      <webElementGuid>c8a17f2f-999f-43f9-b580-e63cfc49c6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fade-menu&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible MuiModal-backdrop muiltr-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]</value>
      <webElementGuid>4656f259-6300-4a42-b036-196ef6a729ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fade-menu']/div</value>
      <webElementGuid>38505e05-acaa-45ce-a9ea-3c8da35a3d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>f2df0541-4e48-42fd-9548-da9a518c13cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
