<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Closed Actions_highcharts-point_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>4ea926f2-bcfc-4438-86ff-4b7b9265d436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect.highcharts-point</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>4f54522f-d81c-4b41-aa00-871a9aefdc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dd22c519-ac43-4dbf-96a2-f91518c67d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3c3269ba-d0a4-41a0-ad35-5b3e46642939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>44a7a046-227a-4c17-9cf8-263dc93d0963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c61c5738-5807-47fb-9ad5-5afa36eab2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#cccccc</value>
      <webElementGuid>286fb4ee-0af1-4a90-8d50-35585bbff8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f6104fe5-d6fc-48c8-9815-d6914dd6c32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ry</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>83dda342-390c-42b8-bd8d-8ff1154208c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point</value>
      <webElementGuid>59c29103-b280-4189-9234-deda220e5278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ac10fc16-87d7-41dd-9cc3-9a3e5123ef51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-qizi2bw-5&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-legend highcharts-no-tooltip&quot;]/g[1]/g[1]/g[@class=&quot;highcharts-legend-item highcharts-pie-series highcharts-color-0 highcharts-legend-item-hidden&quot;]/rect[@class=&quot;highcharts-point&quot;]</value>
      <webElementGuid>9ff1dd70-ea46-441f-b43f-8f4e92b79881</webElementGuid>
   </webElementProperties>
</WebElementEntity>
