<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 10.3.3_highcha_796463</name>
   <tag></tag>
   <elementGuidId>a92f6b26-48cc-4a8f-8a83-df40b8c7261d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect.highcharts-background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>2e07be16-d6e2-4ed8-9730-e1a6dad1206e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>5c75fa8b-1e74-49b8-aba4-71897853a563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-background</value>
      <webElementGuid>5cf37235-d3a1-402a-8193-65ae9c1d211c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>820f513a-b6aa-4b34-8d1c-9d15a37e151c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9d91f9b-654c-4eb9-a2f3-4bbeccc10479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>257</value>
      <webElementGuid>23b94544-8486-44bd-bab0-5bba87c6b86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>84402595-4bab-42bf-8096-2dad878230ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f1f1827-7c75-4471-af5e-bdd0e66ab699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ry</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36b2dcb2-e858-4b73-94e0-838fd09017a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-qizi2bw-5&quot;)/svg[@class=&quot;highcharts-root&quot;]/rect[@class=&quot;highcharts-background&quot;]</value>
      <webElementGuid>c134357e-e1fd-40d8-8d3e-313af01b099a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
