<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_In Process Actions_highcharts-point_1_2_3</name>
   <tag></tag>
   <elementGuidId>1786e210-a13e-4830-b826-f74468b448b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-legend-item.highcharts-pie-series.highcharts-color-2.highcharts-legend-item-hidden > rect.highcharts-point</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>41ab39d0-dd02-4ae4-b6a5-24190f5fa9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>60fdd4c4-ef50-4b7e-bf42-90f59c054f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b771374d-934e-4971-a190-4bf134d90eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>55ce3547-d405-47ab-b0a7-34685bb8f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c7b73b9d-4b90-4974-8436-8a5eab30fc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#cccccc</value>
      <webElementGuid>cdc15754-bb69-4aab-9c0d-a631996c1ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>bf42b63e-cccb-4e34-8949-a7550ec09684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ry</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d72654b6-0daf-4388-adb9-d5bd09d0734d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point</value>
      <webElementGuid>272ea799-c349-45e2-845d-f46bf2f3d7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5e9f5c5d-8097-4016-9520-0f43cd41d9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-cce0rps-5&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-legend highcharts-no-tooltip&quot;]/g[1]/g[1]/g[@class=&quot;highcharts-legend-item highcharts-pie-series highcharts-color-2 highcharts-legend-item-hidden&quot;]/rect[@class=&quot;highcharts-point&quot;]</value>
      <webElementGuid>ee466c66-efd0-4f1a-b6cc-5b347380f9f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
