<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_In Process Actions_highcharts-point_1_2</name>
   <tag></tag>
   <elementGuidId>5f6c55c2-4a19-4dcd-b9aa-8a90d09d07cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-legend-item.highcharts-pie-series.highcharts-color-2 > rect.highcharts-point</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>fb9d1426-47e6-4c47-9d43-a36e11e64416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>115581db-927a-4f9d-8e0a-319af37d43a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c9798e76-a8a5-46bd-8466-2f536c8ee873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>aec1d593-5866-4c6f-b22b-ec8a721bbc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f03b7432-fa08-4dc0-b7f7-10bc6788cf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(119, 195, 236, 1)</value>
      <webElementGuid>b9a8b8d2-b919-40c2-bbda-dbee1b09808c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4b7965f7-5195-4823-ac10-0b9bd36344da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ry</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e7ef0930-8d49-4573-93c7-36a01460f7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point</value>
      <webElementGuid>89d3b455-cbf2-4d43-87d6-f31deebe9848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5d7bb052-5bc2-41a1-88ff-ad3d8c9430c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-cce0rps-5&quot;)/svg[@class=&quot;highcharts-root highcharts-legend-point-active&quot;]/g[@class=&quot;highcharts-legend highcharts-no-tooltip&quot;]/g[1]/g[1]/g[@class=&quot;highcharts-legend-item highcharts-pie-series highcharts-color-2&quot;]/rect[@class=&quot;highcharts-point&quot;]</value>
      <webElementGuid>5173b173-65d4-43e1-84f1-b584a046adcb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
