<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_0</name>
   <tag></tag>
   <elementGuidId>44dc9486-de02-407a-a77e-0a891be68522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>text.highcharts-subtitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[(text() = '0' or . = '0')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43ebbcdf-539a-484d-890b-55f60df6bc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>129</value>
      <webElementGuid>6133f2a3-ea69-4d92-91b4-4e0bf34b52a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>dcb4f556-ce75-4ef1-bc74-a13969615d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-subtitle</value>
      <webElementGuid>1c41c427-07f3-4cb2-b448-d37683df8981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>12427b29-d98f-4635-ad79-817d7a95f177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>188</value>
      <webElementGuid>5d124cd6-fcab-43cb-a0a9-6e946469c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cc126be9-3718-4e74-aea0-50b001305daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-qb4r23v-5&quot;)/svg[@class=&quot;highcharts-root&quot;]/text[@class=&quot;highcharts-subtitle&quot;]</value>
      <webElementGuid>e9d90f6f-f963-49d6-826e-78b52f138649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '0' or . = '0')]</value>
      <webElementGuid>b829e258-7ca4-4dca-86de-2b1d7bcc41d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
