<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee ID_empId</name>
   <tag></tag>
   <elementGuidId>217c9fae-9229-4742-ab5c-281184dd7b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Custom-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Custom-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4495792-57cb-4fa9-b28e-b376892e0516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd06e4cf-19ab-45f2-b72b-505cbc78be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Custom-input</value>
      <webElementGuid>82b1c1ba-361b-4c61-be7e-cd57bbcde439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empId</value>
      <webElementGuid>0c720096-954f-43c4-b4c1-974597a0f1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee ID</value>
      <webElementGuid>be939edb-6e4b-4d50-a46b-66ddac34f1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1393a987-fe43-48fa-adf6-0f2457d4f535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInputBase-inputSizeSmall muiltr-7dqvty-MuiInputBase-input</value>
      <webElementGuid>2dca8cb2-2f3b-425c-9b32-ba4d296b2e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Custom-input&quot;)</value>
      <webElementGuid>d26fe8d3-3e2d-4e92-97b1-de15616b7c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Custom-input']</value>
      <webElementGuid>9bed0c7f-89ae-41dc-8817-b2ac6a1038fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/form/div/div/input</value>
      <webElementGuid>1fa3c6a7-80dc-416a-aa6a-4805a1f7ab28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a5327eea-1563-479d-8496-50129dff739f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Custom-input' and @name = 'empId' and @placeholder = 'Employee ID' and @type = 'text']</value>
      <webElementGuid>9f8dd073-dab7-4173-a40b-95c5fb5aa9ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
