<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Closed On Time</name>
   <tag></tag>
   <elementGuidId>fd8accef-e151-41cb-aa0c-024f84d5478b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-legend-item.highcharts-pie-series.highcharts-color-0 > text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Closed On Time']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71822053-5f84-4446-895c-488251adc0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>d01f677a-00c1-42cc-ade8-46063c679183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>87a0b288-b11b-4b0e-b179-91fc39d857bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6a544ee5-3193-4499-ae10-a3bea4ffda93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>48827aed-a80e-479c-89dc-f8c3eab27ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Closed On Time</value>
      <webElementGuid>ab4e02ce-478d-4c0c-bc5c-07f4ef963360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-siw67g4-4&quot;)/svg[@class=&quot;highcharts-root highcharts-legend-point-active&quot;]/g[@class=&quot;highcharts-legend highcharts-no-tooltip&quot;]/g[1]/g[1]/g[@class=&quot;highcharts-legend-item highcharts-pie-series highcharts-color-0&quot;]/text[1]</value>
      <webElementGuid>680179b6-0892-4d99-82de-ea605f8263b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Closed On Time']/parent::*</value>
      <webElementGuid>5713036e-29a7-4cba-939e-67ed2226b158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Closed On Time' or . = 'Closed On Time')]</value>
      <webElementGuid>bcab1ed8-f3a2-4937-a9ee-f7de2c10518f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
