<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_0</name>
   <tag></tag>
   <elementGuidId>8671d9cb-ba22-40d2-9b5b-d4ea62c9c85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>text.highcharts-subtitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[(text() = '0' or . = '0')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>427657d3-61da-452c-9cc4-7f8c7f46df43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>129</value>
      <webElementGuid>21dcd7f3-fa3b-4672-8ef0-bf7b80e1c214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>e746e6c0-15ba-469c-b27e-baa3c3c3b97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-subtitle</value>
      <webElementGuid>ec0100ce-e5fe-4d65-8c83-35adddc550ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5467c9fa-011e-4053-82dc-a32d2ba85cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>188</value>
      <webElementGuid>6638be10-2a1a-48bd-a2ba-0d1c654454ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11b30c9c-a4c7-4ff3-937c-bebca0ad57d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-siw67g4-4&quot;)/svg[@class=&quot;highcharts-root&quot;]/text[@class=&quot;highcharts-subtitle&quot;]</value>
      <webElementGuid>951c17e1-6512-4d49-9979-311f660ec0d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '0' or . = '0')]</value>
      <webElementGuid>06961b1c-86cc-4b13-a81f-52ae3d46069d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
