<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>b588bca4-1b86-4e87-a99a-5efc22c981a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.MuiTypography-root.MuiTypography-inherit.MuiLink-root.MuiLink-underlineAlways.onboarding-footer-link.muiltr-gn7tr6-MuiTypography-root-MuiLink-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7af405b4-0629-44ce-96ba-bef18e0927a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways onboarding-footer-link muiltr-gn7tr6-MuiTypography-root-MuiLink-root</value>
      <webElementGuid>5455e0b2-b6db-49e3-8be6-14b4bce4eb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>95ca0a40-77d3-4fa6-b01f-f631f84874ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>c9c8976f-6eb0-4755-922d-042a790d7f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;muiltr-1928xwl&quot;]/main[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg auth-container muiltr-9a012d-MuiContainer-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container onboarding-grid muiltr-1ubopdy-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 muiltr-mtpl58-MuiGrid-root&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways onboarding-footer-link muiltr-gn7tr6-MuiTypography-root-MuiLink-root&quot;]</value>
      <webElementGuid>b1336c56-b422-4995-bdc2-548c5c613520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]/a</value>
      <webElementGuid>bc8f81bd-2aa4-4122-be67-adfe750c5dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back')]</value>
      <webElementGuid>dd738a71-54de-487b-912f-0c03c1fead6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::a[1]</value>
      <webElementGuid>8e535ee7-6427-49f3-882c-8f5e0a0059df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/following::a[1]</value>
      <webElementGuid>5dbf0b1c-c3d3-458f-b771-a2ba4bcd50a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>10cc21ce-332a-436a-9a6c-f25cbe7f3088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>ef75273d-9cb3-41a6-a609-f46cce99542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>98c547d1-b3df-41e7-9499-f33be5f35efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>9b0eb63b-f86a-482c-a045-ba0a606e5689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
