<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Back</name>
   <tag></tag>
   <elementGuidId>67918e44-2eb1-48b7-a083-39919761cbd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.muiltr-mtpl58-MuiGrid-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>822a9a0f-bf4f-4237-90f2-0f087a66a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 muiltr-mtpl58-MuiGrid-root</value>
      <webElementGuid>899ec342-c60f-4675-aaba-5436c2c6ada5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>b17574ab-3986-48d8-9baa-768b441a9235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;muiltr-1928xwl&quot;]/main[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg auth-container muiltr-9a012d-MuiContainer-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container onboarding-grid muiltr-1ubopdy-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 muiltr-mtpl58-MuiGrid-root&quot;]</value>
      <webElementGuid>6e4b41b6-1c12-4b51-859d-8dfcb9749069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]</value>
      <webElementGuid>8383dadd-3ee6-495a-9f45-c5d27505e8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[1]</value>
      <webElementGuid>458d2905-755e-45e1-bc5b-7f9a9eee06ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/following::div[3]</value>
      <webElementGuid>cabe4ba2-531c-46a4-ace4-ceb583647012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e4676e83-9dc0-4d2e-8b7e-8005887f88fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>581dc451-db1d-4431-8be9-b9368e918dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
