<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Muhammad Talha Khan a.k.a Afghani</name>
   <tag></tag>
   <elementGuidId>7be970b1-0dd4-4731-a642-a364d0816e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='basic-button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.muiltr-0 > #basic-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7972684-0745-448e-99b6-4d0d9ca33a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium tool-bar__menu-btn muiltr-okb8w1-MuiButtonBase-root-MuiButton-root</value>
      <webElementGuid>37c48972-0763-4894-bae6-28915330f423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa3a1081-745b-4c8a-b8e4-cdd213fdce07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a0d205f-fb1e-4147-ba56-91fa0dfccab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-button</value>
      <webElementGuid>2a285955-3c45-445a-bfda-c321c7e71db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de8c45b9-6a39-4fd2-81f9-04f575df9fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muhammad Talha Khan a.k.a Afghani</value>
      <webElementGuid>2dfbf280-5311-4851-b097-d2b697a47f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex muiltr-1928xwl&quot;]/div[@class=&quot;utility-bar MuiBox-root muiltr-0&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed app-bar mui-fixed muiltr-ii4kgp-MuiPaper-root-MuiAppBar-root&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular tool-bar muiltr-rugrh9-MuiToolbar-root&quot;]/div[@class=&quot;MuiBox-root muiltr-k008qs&quot;]/div[@class=&quot;MuiBox-root muiltr-0&quot;]/button[@id=&quot;basic-button&quot;]</value>
      <webElementGuid>f5fdf163-cea3-44c2-aa09-34c4e7831757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='basic-button'])[2]</value>
      <webElementGuid>16bdf14b-7c87-40af-bcc8-e5e442d59d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/header/div/div[2]/div/button</value>
      <webElementGuid>d99b3a4f-ab8b-4c59-9809-2c184380ff67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::button[2]</value>
      <webElementGuid>e8d80aa8-0d4e-4ce4-b056-81dc4442a410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[1]</value>
      <webElementGuid>b9876f90-9138-46d3-be40-b243a50029fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::button[2]</value>
      <webElementGuid>c4395291-0ee4-4673-8e25-46f7663ef0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Muhammad Talha Khan a.k.a Afghani']/parent::*</value>
      <webElementGuid>bfd33b54-424d-4eae-ac03-4a7cb4fb502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>e57b334c-2982-409f-af54-40f7a780e0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'basic-button' and (text() = 'Muhammad Talha Khan a.k.a Afghani' or . = 'Muhammad Talha Khan a.k.a Afghani')]</value>
      <webElementGuid>069af32c-dd58-451e-aa6d-faca238c0010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
